apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: lb-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.20.10  # Control plane VIP (managed by keepalived)
  ports:
    - port: 6443
      targetPort: 6443
      protocol: TCP
      name: apiserver
  selector:
    component: kube-apiserver



