apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-scripts
  namespace: keepalived
data:
  check_apiserver.sh: |
    #!/bin/bash
    curl --silent --max-time 1 https://127.0.0.1:6443/healthz -k | grep -q ok

