apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: YOUR_TUNNEL_ID
    credentials-file: /etc/cloudflared/creds/credentials.json
    
    ingress:
      # Kong Gateway
      - hostname: kong.yourdomain.com
        service: http://kong-proxy.kong.svc.cluster.local:80
      
      # Grafana
      - hostname: grafana.yourdomain.com
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
      
      # Vault
      - hostname: vault.yourdomain.com
        service: http://vault-internal.vault.svc.cluster.local:8200
      
      # ArgoCD
      - hostname: argocd.yourdomain.com
        service: http://argocd-server.argocd.svc.cluster.local:80
      
      # Catch-all
      - service: http_status:404

