apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: kong
data:
  config.yaml: |
    tunnel: e25489a5-a0e3-4d4c-b6df-0df21545c65d
    credentials-file: /etc/cloudflared/creds/credentials.json
    
    ingress:
      # Kong Gateway
      - hostname: kong.arajeez-cloud.com
        service: http://kong-proxy.kong.svc.cluster.local:80
      
      # Grafana
      - hostname: grafana.arajeez-cloud.com
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
      
      # Vault
      - hostname: vault.arajeez-cloud.com
        service: http://vault-internal.vault.svc.cluster.local:8200
      
      # ArgoCD
      - hostname: argocd.arajeez-cloud.com
        service: http://argocd-server.argocd.svc.cluster.local:80
      
      # Catch-all
      - service: http_status:404

